// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class SecurityToolkitError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "SecurityToolkitError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? SecurityToolkitError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class SecurityToolkitApiPigeonCodecReader: FlutterStandardReader {
}

private class SecurityToolkitApiPigeonCodecWriter: FlutterStandardWriter {
}

private class SecurityToolkitApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return SecurityToolkitApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return SecurityToolkitApiPigeonCodecWriter(data: data)
  }
}

class SecurityToolkitApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = SecurityToolkitApiPigeonCodec(readerWriter: SecurityToolkitApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SecurityToolkitApi {
  func isRooted() throws -> Bool
  func isDebugged() throws -> Bool
  func isLikelyEmulator() throws -> Bool
  func isReverseEngineered() throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SecurityToolkitApiSetup {
  static var codec: FlutterStandardMessageCodec { SecurityToolkitApiPigeonCodec.shared }
  /// Sets up an instance of `SecurityToolkitApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SecurityToolkitApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let isRootedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.security_toolkit.SecurityToolkitApi.isRooted\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isRootedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isRooted()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isRootedChannel.setMessageHandler(nil)
    }
    let isDebuggedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.security_toolkit.SecurityToolkitApi.isDebugged\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isDebuggedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isDebugged()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isDebuggedChannel.setMessageHandler(nil)
    }
    let isLikelyEmulatorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.security_toolkit.SecurityToolkitApi.isLikelyEmulator\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isLikelyEmulatorChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isLikelyEmulator()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isLikelyEmulatorChannel.setMessageHandler(nil)
    }
    let isReverseEngineeredChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.security_toolkit.SecurityToolkitApi.isReverseEngineered\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isReverseEngineeredChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isReverseEngineered()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isReverseEngineeredChannel.setMessageHandler(nil)
    }
  }
}
