name: Pull Request

on: [workflow_dispatch, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: kuhnroyal/flutter-fvm-config-action/setup@c378498f1d1962d33039c3989411093ef8a17b2c # v3.3.0
      - name: Download dependencies
        run: |
          flutter --version
          flutter pub get
      - name: Run unit tests
        run: |
          dart run test test/unit